version: "3.4"

services:
  # Apache Pinot services
  pinot-controller:
    image: apachepinot/pinot:0.12.1
    container_name: "pinot-controller"
    command: "StartController -zkAddress zookeeper:2181"
    restart: unless-stopped
    ports:
      - "9000:9000"
    #depends_on:
    #  - zookeeper
    networks:
      - rta_scratch
  pinot-broker:
    image: apachepinot/pinot:0.12.1
    container_name: "pinot-broker"
    command: "StartBroker -zkAddress zookeeper:2181"
    restart: unless-stopped
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks:
      - rta_scratch
  pinot-server:
    image: apachepinot/pinot:0.12.1
    container_name: "pinot-server"
    command: "StartServer -zkAddress zookeeper:2181"
    restart: unless-stopped
    depends_on:
      - pinot-broker
    networks:
      - rta_scratch
  pinot-add-tables:
    image: apachepinot/pinot:0.12.1
    container_name: "pinot-add-tables"
    restart: on-failure
    environment:
      - "JAVA_OPTS=-Dpinot.admin.system.exit=true"
    volumes:
      - ./pinot/config:/config
    #command: "'./bin/pinot-admin.sh AddTable -schemaFile /config/orders/schema.json -tableConfigFile /config/orders/table.json -controllerHost pinot-controller -exec'"
    #command: "'./bin/pinot-admin.sh AddTable -schemaFile /config/orders/schema.json -tableConfigFile /config/orders/table_with_index.json -controllerHost pinot-controller -exec'"
    #command: "'./bin/pinot-admin.sh AddTable -schemaFile /config/orders/schema.json -tableConfigFile /config/orders/table_with_index.json -controllerHost pinot-controller -exec && \
    #           ./bin/pinot-admin.sh AddTable -schemaFile /config/order_items_enriched/schema.json -tableConfigFile /config/order_items_enriched/table.json -controllerHost pinot-controller -exec'"
    #command: "'sleep 30 && \
    #           ./bin/pinot-admin.sh AddTable -schemaFile /config/orders/schema.json -tableConfigFile /config/orders/table_with_index.json -controllerHost pinot-controller -exec && \
    #           ./bin/pinot-admin.sh AddTable -schemaFile /config/order_items_enriched/schema.json -tableConfigFile /config/order_items_enriched/table.json -controllerHost pinot-controller -exec'"
    command: "'sleep 30 && \
               ./bin/pinot-admin.sh AddTable -schemaFile /config/orders/schema.json -tableConfigFile /config/orders/table_with_index.json -controllerHost pinot-controller -exec && \
               ./bin/pinot-admin.sh AddTable -schemaFile /config/order_items_enriched/schema.json -tableConfigFile /config/order_items_enriched/table.json -controllerHost pinot-controller -exec && \
               ./bin/pinot-admin.sh AddTable -schemaFile /config/orders_enriched/schema.json -tableConfigFile /config/orders_enriched/table.json -controllerHost pinot-controller -exec && \
               ./bin/pinot-admin.sh AddTable -schemaFile /config/deliveryStatuses/schema.json -tableConfigFile /config/deliveryStatuses/table.json -controllerHost pinot-controller -exec'"
    entrypoint: "bash -c"
    depends_on:
      - pinot-controller
    networks:
      - rta_scratch

networks:
  rta_scratch:
    name: rta_scratch
